### ISSUE TITLE
Templating : Add URL buttons

### ISSUE THREAD

**Issue by RorFis** [grafana/alerting#177]
Using the default template we have access to visual informations like the colored firing state and also Panel, Dashboard and Silence URL : 

![LCgTY](https://github.com/grafana/alerting/assets/97751880/adbc517d-840d-4cd9-98a0-a6c4314122ab)

However, it seems that this feature is not working when using custom templates. I tried to use the default template as a custom template and the result is different : 

![image](https://github.com/grafana/alerting/assets/97751880/86d5fa44-7fa4-459f-a0fc-8f145343c74d)

As you can see, no buttons, no colored state. Is there a way to add this ?

**Comment by gillesdemey** [comment]
Hi! You can edit and compile the default email templates that ship with Grafana by following [these instructions](https://github.com/grafana/grafana/tree/main/emails). Through the UI we do not allow editing the HTML structure of the email template when using custom templates and fall back to rendering them as a text-only format.

As an aside, what parts of the default template are not working for your use-case?

**Comment by RorFis** [comment]
Hi, thanks for your response.
I actually wanted to have a bit less information in the email notification for my use case. That's not a big deal though, i'll stick to the default !

**Comment by gillesdemey** [comment]
Cleaning up the board a bit; closing this one :)
