### ISSUE TITLE
Pending period in the Grafana UI is bound to the wrong value

### ISSUE THREAD

**Issue by Fresa** [grafana/alerting#180]
It seems pending period is bound to the evaluation interval when the UI for an alert rule is loaded even if there is a custom pending period defined.
In the following example an evaluation group has been assigned with the Evaluation interval of 1m. A pending period of 30m has been configured, incorrectly visualized as 1m. If you look in the edit evaluation group modal you can see the rule having a pending period of 30m. If I save the rule now the pending period will become 1m.

<img width="653" alt="image" src="https://github.com/grafana/alerting/assets/1190300/652a3c8a-3e17-49c2-8372-70bb4ffd7231">

<img width="323" alt="image" src="https://github.com/grafana/alerting/assets/1190300/075a88ee-74ba-4da7-a27b-32129172ddad">

Grafana v11.1.0-69051 (9d44c8e8cf)

**Comment by Fresa** [comment]
Maybe this should be reported under the Grafana project?

**Comment by soniaAguilarPeiron** [comment]
Closing this one as the duplicated is already fixed
